version: '3.9'
services:

  todo-db:
    image: mariadb:10.7.1
    container_name: todo-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: node-todo
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - app-network
  
  todo-api:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
    networks:
      - app-network
    
volumes:
  mariadbdata:

networks:
  app-network:
    driver: bridge
